export const mockUser: User = {
  $id: "usr_001",
  email: "dangkhoa@example.com",
  userId: "usr_001",
  dwollaCustomerUrl: "https://api.dwolla.com/customers/12345",
  dwollaCustomerId: "12345",
  firstName: "Khoa",
  lastName: "Dang",
  name: "Khoa Dang",
  address1: "123 Main St",
  city: "Los Angeles",
  state: "CA",
  postalCode: "90001",
  dateOfBirth: "2003-01-01",
  ssn: "123-45-6789",
};

export const mockBanks: Bank[] = [
  {
    $id: "bank_001",
    accountId: "acc_001",
    bankId: "bank_a",
    accessToken: "access_token_1",
    fundingSourceUrl: "https://api.dwolla.com/funding-sources/abc123",
    userId: "usr_001",
    shareableId: "share_001",
  },
  {
    $id: "bank_002",
    accountId: "acc_002",
    bankId: "bank_b",
    accessToken: "access_token_2",
    fundingSourceUrl: "https://api.dwolla.com/funding-sources/xyz789",
    userId: "usr_001",
    shareableId: "share_002",
  },
  {
    $id: "bank_003",
    accountId: "acc_003",
    bankId: "bank_c",
    accessToken: "access_token_3",
    fundingSourceUrl: "https://api.dwolla.com/funding-sources/uvw456",
    userId: "usr_001",
    shareableId: "share_003",
  },
];

export const mockAccounts: Account[] = [
  {
    id: "acc_001",
    name: "Bank A",
    officialName: "Bank A Official",
    currentBalance: 5000,
    availableBalance: 4800,
    mask: "1234",
    institutionId: "inst_001",
    shareableId: "share_001",
    appwriteItemId: "bank_a",
    type: "checking",
    subtype: "Personal",
  },
  {
    id: "acc_002",
    name: "Bank B",
    officialName: "Bank B Official",
    currentBalance: 12000,
    availableBalance: 11800,
    mask: "5678",
    institutionId: "inst_002",
    shareableId: "share_002",
    appwriteItemId: "bank_b",
    type: "savings",
    subtype: "Business",
  },
  {
    id: "acc_003",
    name: "Bank C",
    officialName: "Bank C Official",
    currentBalance: 8000,
    availableBalance: 7800,
    mask: "9876",
    institutionId: "inst_003",
    shareableId: "share_003",
    appwriteItemId: "bank_c",
    type: "investment",
    subtype: "Investment",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    $id: "txn_001",
    name: "Grocery Store",
    paymentChannel: "Credit Card",
    type: "debit",
    accountId: "acc_001",
    amount: 45.99,
    pending: false,
    category: "Groceries",
    date: "2024-02-20T14:30:00Z",
    image: "https://via.placeholder.com/50",
    $createdAt: "2024-02-20T14:30:00Z",
    channel: "Online",
    senderBankId: "bank_a",
    receiverBankId: "bank_b",
  },
  {
    id: "txn_002",
    $id: "txn_002",
    name: "Salary Deposit",
    paymentChannel: "Bank Transfer",
    type: "credit",
    accountId: "acc_002",
    amount: 2500.0,
    pending: false,
    category: "Income",
    date: "2024-02-18T09:00:00Z",
    image: "https://via.placeholder.com/50",
    $createdAt: "2024-02-18T09:00:00Z",
    channel: "Direct Deposit",
    senderBankId: "bank_c",
    receiverBankId: "bank_b",
  },
  {
    id: "txn_003",
    $id: "txn_003",
    name: "Electricity Bill",
    paymentChannel: "Bank Transfer",
    type: "debit",
    accountId: "acc_001",
    amount: 120.5,
    pending: true,
    category: "Utilities",
    date: "2024-02-15T18:45:00Z",
    image: "https://via.placeholder.com/50",
    $createdAt: "2024-02-15T18:45:00Z",
    channel: "Bank Transfer",
    senderBankId: "bank_b",
    receiverBankId: "bank_d",
  },
  {
    id: "txn_004",
    $id: "txn_004",
    name: "Restaurant Dinner",
    paymentChannel: "Debit Card",
    type: "debit",
    accountId: "acc_003",
    amount: 75.25,
    pending: false,
    category: "Dining",
    date: "2024-02-10T20:15:00Z",
    image: "https://via.placeholder.com/50",
    $createdAt: "2024-02-10T20:15:00Z",
    channel: "POS",
    senderBankId: "bank_a",
    receiverBankId: "bank_d",
  },
  {
    id: "txn_005",
    $id: "txn_005",
    name: "Freelance Payment",
    paymentChannel: "PayPal",
    type: "credit",
    accountId: "acc_002",
    amount: 600.0,
    pending: false,
    category: "Freelance",
    date: "2024-02-08T12:00:00Z",
    image: "https://via.placeholder.com/50",
    $createdAt: "2024-02-08T12:00:00Z",
    channel: "Online",
    senderBankId: "bank_e",
    receiverBankId: "bank_b",
  },
];

export const mockTotalBanks = mockAccounts.length;

export const mockTotalCurrentBalance = mockAccounts.reduce(
  (sum, account) => sum + account.currentBalance,
  0
);

export const mockHeaderBoxData: HeaderBoxProps = {
  type: "greeting",
  title: "Welcome,",
  subtext: "Here is your financial overview.",
  user: mockUser.name,
};

export const mockBankCardData: CreditCardProps = {
  account: mockAccounts[0],
  userName: mockUser.name,
  showBalance: true,
};
